using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SirKato.XrmToolBox.IconGallery
{
    /// <summary>
    /// This class can help you to store settings for your plugin
    /// </summary>
    /// <remarks>
    /// This class must be XML serializable
    /// </remarks>
    public class Settings
    {
        public const int DEFAULT_IMAGE_SIZE = 32;
        public const string DEFAULT_TO_BIG_IMAGE_BASE64 = "iVBORw0KGgoAAAANSUhEUgAAAGAAAABlCAIAAAA9N3HcAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAJOgAACToAYJjBRwAAAMgSURBVHhe7ZtRloMgDEVnXS7I9bgaN+NiOqC0RwLkkZ5S48y7f3M0rbkTUAn9eRAVCgJQEICCABQEoCAABQEoCEBBAAoCUBCAggBNQev8Y2ZathQt2LZ1madAOvEg/D3Py7o1gnzQErQteTJ9zGsKf7Gtc8cHTdFTinDGSEF9cl406+9Sxg2xj47R67BM0nnK5XA6USnAfRid8g/zUqXA3CkaI6ionrk1xRQmvRkaIkj40XMuFKml+XVGCBJ+YMImn99mgCCrn3civsfnBYkh01MPb4R8DQoCUBCAggAuBOUf3PzkS/i8IHu6QumfF2TO13MBjRAkEwYZu66fMYIKQ+2JKLywplOeOPMzRlBRFYFpCi+sJ03HImM6+MKbnlGCqoow/vSMExQwric2V0SuZaCgQFwT67DkVU7EIigbNtPSPR726SY2NVLoQWxyuO9p2AT9SygIQEEACgJQEICCABQEoCAABQEoCEBBAAoCUBCAggAUBKAgAAUBKAhAQQAKAlAQgIIAT0H6zwZgi2a1doS2dan/vGX/fYujNtlTULGJoEGjx2do2/f1EuM3udhoZhUUqeTfJ8jasPewF+8dQRUDHYJsrfoDrRS/RF1QdmGxcyxyK/61SFCtdsppbYtfdd4Ucw9BO6LC5Al6eKknzOPq6Dk2D/kdYrAETIKEXBd5d/NeBRXHtcPCz6309AmSz0iVFJVw4ad075u6IIV6AbQFgbHpHpug/b6TIjJ6BRV6te8ND6XprAsxV1Cg8jTdFpQfkYJqt/8TDgy9IygiLv2/CRIXVtvTnKfaDjc9H0juIuhA5JIZUsJFmJ6zvyndIEhLVQmXo0hN+t6ClKvXwqUhLe1bCxIF1DvEAiIyxLZ2jt9VUJili8WK7Bzkt1AUOF7mT6L2e0E6eOBWEEbcr5GgeIY03MFdBZWPuFhQoJiMEPKp6QrMgurTR5egiN4cyPCxKP0UBC48dRuaF2ztahwrh/WmhlxnvJanINKAggAUBKAgAAUBKAhAQQAKAlAQgIIAFASgIAAFASgIQEEACgJQEICCABQEoCAABak8Hr9hMsyAiYqIvAAAAABJRU5ErkJggg==";
        public const string DEFAULT_ERROR_IMAGE_BASE64 = "iVBORw0KGgoAAAANSUhEUgAAAGAAAABlCAIAAAA9N3HcAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAJOgAACToAYJjBRwAAALCSURBVHhe7ZpBjqMwEEXnIL2c07DiLFlwFiSOgjhKcoNeIBZRJCSaNEUUqLI/Q2oCKP+pdjHf8TPGJt1/OhKFggAUBKAgAAUBKAhAQQAKAlAQgIIAFASgIAAFASgIQEEACgJQEOATBbV5Vn/9/X5Ukt3O8pHmAwVdrsmTnd+q84t8qJgKKouJ2gVlRJfT+TErSesku+ZVK9eE8U2784Kg22l+Ja5TJRcLRvfxqk9F+A73TRP0MJtSPtJsL+i30qs9Kt804YiC+spukvCMb5rwVkFq9a4eknbd45smeAqKXBlAD2l+w7fn6npKp22G0tPumybsXdBAm+tR6Za+acIxBHVd1Uya3Ut155smKJtBlT0bCtItXxG0JE2gIKmDCzrrU7tu6ZsmHELQRff1nRTqXcE3TfAUFK2FR7tZ95e2LJp5m3tZL0S+acLbBNmTqYa0rOwJ900bKbNp+9ixex+CguPxTRs5kqAkbcrgWvBOG3mXoIXPoEjB8fimjTgK8tjFQNXht0rvtJGdCXpaif2LpTXg8I7jmzayX0F3rDNL8Cv6po3MTpXRh/r7BZmn3tC0+6aN7F2Q1VFg2n3THkzWZp3HHlvbCDKn3erLN20NGwkympm3um/aGrYSpLcSs6Vv2oOqSR6vY+lLSwwX/qtG6IsavwH+5zThn+6DlwXN7+TlQ9Jv1X3NHq6+aQM6M7brbSlowQ7tmzZg3Gt7FWRN5jTQN23AaLZU0Ip/XtDr/JanzyF1UsSOJLrH6ZB80wbWP4M+hrW7GNFQEICCABQEoCAABQEoCEBBAAoCUBCAggAUBKAgAAUBKAhAQQAKAlAQgIIAFASgIAAFASgIQEEACgJQEICCABQEoCAABQEoCEBBAAoCUBCAggAUBKAgAAUBKAhAQQAKAlAQgIIAFASgIAAFASgIQEEACgJQEICConTdDx/tnvFUvXa9AAAAAElFTkSuQmCC";
        public string LastUsedOrganizationWebappUrl { get; set; }

        public int ImageSize { get; set; }

        public string ErrorImage { get; set; }

        public string FileToBigImage { get; set; }

    }
}